### ISSUE TITLE
Cmake variables are not translated to parent scope with add_subdirectory

### ISSUE THREAD

**Issue by ClausKlein** [aminya/cpp_vcpkg_project#1]
Some of the used `CMake` variable are not exported to parent scope.

It is not clear to me how  this works, if it works right?
The exported packages are not checked so the result is undefined!

see https://github.com/ClausKlein/cpp_cmake_project/runs/6308595865?check_suite_focus=true#step:6:81
and https://github.com/ClausKlein/cpp_cmake_project/commit/5085bd4b1b76d40488ab7752272f7ee736f47824

**Comment by aminya** [comment]
These are local variables. They are not exported.

**Comment by ClausKlein** [comment]
see too https://github.com/ClausKlein/cpp_cmake_project/commit/bbe0fd6be37b2b131af83917c0923c3cd29c69fd#diff-214006f43fd1197bb996e5f778e53bbcba05006d1286804b81dbef47c4bd9b44L12

**Comment by ClausKlein** [comment]
**IMHO** some of the `CMake` settings are magic (or obscure)
see https://github.com/ClausKlein/cpp_cmake_project/pull/1/files

**Comment by aminya** [comment]
The variables are automatically passed to the parent scope when `add_subdirectory` is used.

**Comment by aminya** [comment]
I was wrong about add_subdirectory. The variables are not passed to the parent scope.
